### ISSUE TITLE
Missing "docs/README.md" in the latest version 3.5.6

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlhub#115]
This may be because `README.md` was moved into `docs/`, while previously it was in the same level of `docs`.

```console
test@vbvm:~$ pip3 install mlhub==3.5.6
Collecting mlhub==3.5.6
  Using cached https://files.pythonhosted.org/packages/c5/da/ebf9043a264d206e1c830a1e63cab24031d89ef2d7adb904768c5c07708f/mlhub-3.5.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5axviuvn/mlhub/setup.py", line 22, in <module>
        with open(path.join(here, 'docs/README.md'), encoding='utf-8') as f:
      File "/usr/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-5axviuvn/mlhub/docs/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5axviuvn/mlhub/
test@vbvm:~$ ls
Desktop  Documents  Downloads  Music  Pictures  Programs  Public  Templates  Videos
test@vbvm:~$ wget https://files.pythonhosted.org/packages/c5/da/ebf9043a264d206e1c830a1e63cab24031d89ef2d7adb904768c5c07708f/mlhub-3.5.6.tar.gz
--2019-12-26 09:37:50--  https://files.pythonhosted.org/packages/c5/da/ebf9043a264d206e1c830a1e63cab24031d89ef2d7adb904768c5c07708f/mlhub-3.5.6.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.9.63, 2a04:4e42:2::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.9.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52295 (51K) [binary/octet-stream]
Saving to: ‘mlhub-3.5.6.tar.gz’

mlhub-3.5.6.tar.gz                            100%[================================================================================================>]  51.07K  --.-KB/s    in 0.006s  

2019-12-26 09:37:50 (8.77 MB/s) - ‘mlhub-3.5.6.tar.gz’ saved [52295/52295]

test@vbvm:~$ ls
Desktop  Documents  Downloads  mlhub-3.5.6.tar.gz  Music  Pictures  Programs  Public  Templates  Videos
test@vbvm:~$ tar xf mlhub-3.5.6.tar.gz 
test@vbvm:~$ ls
Desktop  Documents  Downloads  mlhub-3.5.6  mlhub-3.5.6.tar.gz  Music  Pictures  Programs  Public  Templates  Videos
test@vbvm:~$ cd mlhub-3.5.6/
test@vbvm:~/mlhub-3.5.6$ ls
LICENSE  MANIFEST.in  mlhub  mlhub.egg-info  PKG-INFO  setup.cfg  setup.py
test@vbvm:~/mlhub-3.5.6$ cd mlhub
test@vbvm:~/mlhub-3.5.6/mlhub$ ls
bash_completion.d  commands.py  constants.py  __init__.py  pkg.py  scripts  utils.py
test@vbvm:~/mlhub-3.5.6/mlhub$ 
test@vbvm:~$ pip3 install mlhub==3.5.5
Collecting mlhub==3.5.5
  Downloading https://files.pythonhosted.org/packages/4c/21/8e19c6dcee72ab0439c59b457e88d3ecb56efa1c6dabaa6b5807f69ca695/mlhub-3.5.5.tar.gz (51kB)
    100% |████████████████████████████████| 61kB 4.6MB/s 
Collecting distro (from mlhub==3.5.5)
  Using cached https://files.pythonhosted.org/packages/ea/35/82f79b92fa4d937146c660a6482cee4f3dfa1f97ff3d2a6f3ecba33e712e/distro-1.4.0-py2.py3-none-any.whl
Collecting fuzzywuzzy (from mlhub==3.5.5)
  Using cached https://files.pythonhosted.org/packages/d8/f1/5a267addb30ab7eaa1beab2b9323073815da4551076554ecc890a3595ec9/fuzzywuzzy-0.17.0-py2.py3-none-any.whl
Collecting python-Levenshtein (from mlhub==3.5.5)
Collecting pyyaml (from mlhub==3.5.5)
Collecting requests (from mlhub==3.5.5)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting yamlordereddictloader (from mlhub==3.5.5)
Collecting setuptools (from python-Levenshtein->mlhub==3.5.5)
  Using cached https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->mlhub==3.5.5)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->mlhub==3.5.5)
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->mlhub==3.5.5)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->mlhub==3.5.5)
  Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
Building wheels for collected packages: mlhub
  Running setup.py bdist_wheel for mlhub ... done
  Stored in directory: /home/test/.cache/pip/wheels/ca/fc/bf/61fb0ad5636f6387c6b10b6c1e45ac200ba2451a0a190b8402
Successfully built mlhub
Installing collected packages: distro, fuzzywuzzy, setuptools, python-Levenshtein, pyyaml, chardet, urllib3, idna, certifi, requests, yamlordereddictloader, mlhub
Successfully installed certifi-2019.11.28 chardet-3.0.4 distro-1.4.0 fuzzywuzzy-0.17.0 idna-2.8 mlhub-3.5.5 python-Levenshtein-0.12.0 pyyaml-5.2 requests-2.22.0 setuptools-42.0.2 urllib3-1.25.7 yamlordereddictloader-0.4.0
test@vbvm:~$ wget https://files.pythonhosted.org/packages/4c/21/8e19c6dcee72ab0439c59b457e88d3ecb56efa1c6dabaa6b5807f69ca695/mlhub-3.5.5.tar.gz
--2019-12-26 09:43:50--  https://files.pythonhosted.org/packages/4c/21/8e19c6dcee72ab0439c59b457e88d3ecb56efa1c6dabaa6b5807f69ca695/mlhub-3.5.5.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.9.63, 2a04:4e42:2::319
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.9.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51594 (50K) [binary/octet-stream]
Saving to: ‘mlhub-3.5.5.tar.gz’

mlhub-3.5.5.tar.gz     100%[===========================>]  50.38K  --.-KB/s    in 0.006s  

2019-12-26 09:43:50 (8.63 MB/s) - ‘mlhub-3.5.5.tar.gz’ saved [51594/51594]

test@vbvm:~$ tar xf mlhub-3.5.5.tar.gz 
test@vbvm:~$ cd mlhub-3.5.5/
test@vbvm:~/mlhub-3.5.5$ ls
LICENSE  MANIFEST.in  mlhub  mlhub.egg-info  PKG-INFO  README.md  setup.cfg  setup.py
test@vbvm:~/mlhub-3.5.5$ cd mlhub
test@vbvm:~/mlhub-3.5.5/mlhub$ ls
bash_completion.d  commands.py  constants.py  __init__.py  pkg.py  scripts  utils.py
test@vbvm:~/mlhub-3.5.5/mlhub$
```

**Comment by gjwgit** [comment]
Missed updating the MANIFEST.in with new README.md location. Fixed in 7eaafed43d6fc9387ddfa00503c5446fead8fbed
