### ISSUE TITLE
objects: update re use of tensorflow.contrib

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#191]
Current error below. The contrib module was merged into tensorflow itself?

```
$ ml demo objects
Loading the required Python modules for the ResNet152 model ...

Traceback (most recent call last):
  File "demo.py", line 5, in <module>
    from objreg_utils import (
  File "/home/gjw/.mlhub/objects/objreg_utils.py", line 19, in <module>
    from tensorflow.contrib.slim.nets import resnet_v1
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by JingjingShii** [comment]
Tensorflow2.2 or later only supports Python 3.8 (we are using Python 3.8.5 and tensorflow 2.4.1) (https://www.tensorflow.org/install/pip)
There is no contrib module in TF2.0 since tensorflow.crontrib only supports 1.1X. https://github.com/tensorflow/tensorflow/issues/31350#issuecomment-542827486() 

I think the only way is to find another module to substitute this one.
