### ISSUE TITLE
Missing README needs to fail gracefully

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#204]
If a package does not include a readme the README command should fail gracefully. Currently it includes a trackback and should not!

```
$ ml readme zynlp 

mlhub: The 'zynlp' model does not have a 'README.txt' file:
  /home/gjw/.mlhub/zynlp/README.txt

Traceback (most recent call last):
  File "/home/gjw/.local/lib/python3.8/site-packages/mlhub/__init__.py", line 208, in main
    args.func(args)
  File "/home/gjw/.local/lib/python3.8/site-packages/mlhub/commands.py", line 617, in readme
    raise utils.ModelReadmeNotFoundException(model, readme_file)
mlhub.utils.ModelReadmeNotFoundException: ('zynlp', '/home/gjw/.mlhub/zynlp/README.txt')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gjw/.local/bin/ml", line 8, in <module>
    sys.exit(main())
  File "/home/gjw/.local/lib/python3.8/site-packages/mlhub/__init__.py", line 281, in main
    utils.print_commands_suggestions_on_stderr('remove', 'install')
  File "/home/gjw/.local/lib/python3.8/site-packages/mlhub/utils.py", line 769, in print_commands_suggestions_on_stderr
    print_on_stderr(get_command_suggestion(cmd))
  File "/home/gjw/.local/lib/python3.8/site-packages/mlhub/utils.py", line 2553, in print_on_stderr
    print(msg.format(*param), file=sys.stderr)
AttributeError: 'NoneType' object has no attribute 'format'

```

**Comment by gjwgit** [comment]
The pull request seems to have broken the README command:

```
$ ml --version
mlhub version 3.7.9

$ ml readme zynlp

mlhub: The 'zynlp' model does not have a 'README.txt' file.

$ ml readme azspeech

mlhub: The 'azspeech' model does not have a 'README.txt' file.

$ ml readme rain

mlhub: The 'rain' model does not have a 'README.txt' file.
```

**Comment by gjwgit** [comment]
Error introduced as  603cb0e038db8c32c6cbdb438bafeefe6e07e7dc.

How does the introduced `else` path recognise a missing README?

Revert and release 3.7.10 to PyPI

That seems to have fixed the issue.
