### ISSUE TITLE
README gracefully handle missing readme files

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#49]
```
$ ml readme colorize
Traceback (most recent call last):
  File "/home/fred/projects/mlhub/mlhub/__init__.py", line 140, in <module>
    main()
  File "/home/fred/projects/mlhub/mlhub/__init__.py", line 137, in main
    args.func(args)
  File "/home/fred/homecloud/projects/mlhub/mlhub/commands.py", line 380, in readme
    with open(readme, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/fred/.mlhub/colorize/README.txt'

```

**Comment by gjwgit** [comment]
Fixed 40b001afe4a379d82b284ca1c9b334656b4c6dc3
