### ISSUE TITLE
INSTALL: Handle exceptions from GitHub

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlhub#65]
Below are two examples of non-existent GitHub refs: 
```console
$ ml install gjwgit/animate#1 
Traceback (most recent call last): 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/__init__.py", line 202, in main 
    args.func(args) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/commands.py", line 225, in install_model 
    mlhubyaml = utils.get_pkgyaml_github_url(model) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/utils.py", line 535, in get_pkgyaml_github_url 
    return get_available_pkgyaml(url) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/utils.py", line 566, in get_available_pkgyaml 
    raise DescriptionYAMLNotFoundException(url) 
mlhub.utils.DescriptionYAMLNotFoundException: https://api.github.com/repos/gjwgit/animate/contents/{}?ref=pull/1/head 
 
During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
  File "/home/simon/anaconda3/bin/ml", line 11, in <module> 
    sys.exit(main()) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/__init__.py", line 247, in main 
    utils.print_error(msg, e.args[0]) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/utils.py", line 947, in print_error 
    print_on_stderr(APPX + msg.format(*param)) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/utils.py", line 934, in print_on_stderr 
    print(msg.format(*param), file=sys.stderr) 
IndexError: tuple index out of range 

$ ml install gjwgit/animate@aaa 
Traceback (most recent call last): 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/__init__.py", line 202, in main 
    args.func(args) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/commands.py", line 225, in install_model 
    mlhubyaml = utils.get_pkgyaml_github_url(model) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/utils.py", line 535, in get_pkgyaml_github_url 
    return get_available_pkgyaml(url) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/utils.py", line 566, in get_available_pkgyaml 
    raise DescriptionYAMLNotFoundException(url) 
mlhub.utils.DescriptionYAMLNotFoundException: https://api.github.com/repos/gjwgit/animate/contents/{}?ref=aaa 
 
During handling of the above exception, another exception occurred: 
 
Traceback (most recent call last): 
  File "/home/simon/anaconda3/bin/ml", line 11, in <module> 
    sys.exit(main()) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/__init__.py", line 247, in main 
    utils.print_error(msg, e.args[0]) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/utils.py", line 947, in print_error 
    print_on_stderr(APPX + msg.format(*param)) 
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/utils.py", line 934, in print_on_stderr 
    print(msg.format(*param), file=sys.stderr) 
IndexError: tuple index out of range
```

**Comment by simonzhaoms** [comment]
Solved after commit 540dcc8
