### ISSUE TITLE
INSTALL: Failed if no `meta` -> `url` in Packages.yaml

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlhub#70]
Need gracefully deal with this kind of exception:

```console
$ ml install beeswarm 
Traceback (most recent call last):
  File "/home/simon/anaconda3/bin/ml", line 11, in <module>
    sys.exit(main())
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/__init__.py", line 202, in main
    args.func(args)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/commands.py", line 211, in install_model
    url, version, meta_list = utils.get_model_info_from_repo(model, args.mlhub)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/mlhub/utils.py", line 1000, in get_model_info_from_repo
    url = entry["meta"]["url"]
KeyError: 'url'
```

**Comment by gjwgit** [comment]
Let's drop the use of filename: and rely on using url: only where we specific either a directory or a .mlm filename perhaps for a stable packaged release. Note that url: (and currently filename:) are only relevant to the curated Packages.yaml file on mlhub.ai. A url: is a requirement for each entry in Packages.yaml.
